version: '3.9'

services:

  # api:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #     # Only will build development stage from our dockerfile
  #   volumes:
  #     - .:/usr/src/app
  #   # Run a command against the development stage of the image
  #   command: npm run start:dev
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - node-postgres
  #   depends_on:
  #     - db
  
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - node-postgres
    # This is for PROD only 
    # expose:
    #   - 5432
    ports:
      - "5432:5432"

volumes:
  db-data:
networks:
  node-postgres:



#Please note - if your NestJS image already exists (for example, if you tested building the full image in the Dockerfile above), 
#you can run (docker-compose up -d --build) to rebuild the image.